const checkEnvVariables = require("./check-env-variables")

checkEnvVariables()

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  reactStrictMode: true,
  devIndicators: false,
  // Next 16 removed the `eslint` config block — lint no longer runs as part
  // of `next build`. Use `pnpm lint` (standalone) to check. The repo has
  // ~24 pre-existing lint errors (mostly missing react/jsx-key in animation
  // demo components under src/modules/test/) that are tracked as a separate
  // clean-up task.
  //
  // TypeScript errors DO break the prod build (was previously suppressed
  // via `ignoreBuildErrors: true`). Baseline verified clean.
  typescript: {
    ignoreBuildErrors: false,
  },
  images: {
    /** Set NEXT_PUBLIC_UNOPTIMIZED_IMAGES=true to skip the image optimizer (debug / broken remote hosts). Default: optimized WebP/AVIF + sizing via `/_next/image`. */
    unoptimized: process.env.NEXT_PUBLIC_UNOPTIMIZED_IMAGES === "true",
    remotePatterns: [
      {
        protocol: "http",
        hostname: "localhost",
      },
      { 
        protocol: "https",
        // Fallback to localhost if missing to prevent Next.js build crash
        hostname: process.env.NEXT_PUBLIC_BASE_URL ? process.env.NEXT_PUBLIC_BASE_URL.replace(/^https?:\/\//, '') : 'localhost',
      },
      { 
        protocol: "https",
        hostname: process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL ? process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL.replace(/^https?:\/\//, '') : 'localhost',
      },
      { 
        protocol: "https",
        hostname: "medusa-public-images.s3.eu-west-1.amazonaws.com",
      },
      { 
        protocol: "https",
        hostname: "medusa-server-testing.s3.amazonaws.com",
      },
      { 
        protocol: "https",
        hostname: "medusa-server-testing.s3.us-east-1.amazonaws.com",
      },
      { 
        protocol: "https",
        // Added regex strip to ensure https:// doesn't crash the hostname
        hostname: process.env.NEXT_PUBLIC_MINIO_ENDPOINT ? process.env.NEXT_PUBLIC_MINIO_ENDPOINT.replace(/^https?:\/\//, '') : 'localhost',
      },
      {
        protocol: "https",
        hostname: "cdn.fashionbizapps.nz",
      },
      {
        protocol: "https",
        hostname: "cdn11.bigcommerce.com",
      },
      {
        protocol: "https",
        hostname: "www.dncworkwear.com.au",
      },
      {
        protocol: "https",
        hostname: "dncworkwear.com.au",
      },
    ],
  },
  // ──────────────────────────────────────────────────────────────────
  // Server-Action ID stability across deploys
  //
  // Symptom: after a Vercel deploy, any tab that was open before the
  // deploy throws `Server Action "<hash>" was not found on the server`
  // when the customer next clicks something (e.g. "Add to cart").
  // That hashed ID was generated by the previous build and the new
  // server doesn't recognise it.
  //
  // Fix: set the env var `NEXT_SERVER_ACTIONS_ENCRYPTION_KEY` in the
  // Vercel project (Production + Preview). Next.js 15 reads it from
  // `process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY` automatically
  // (see `next/dist/esm/server/app-render/encryption-utils.js`) and
  // uses it instead of the per-build random key. Same key across
  // deploys → same action IDs → tabs survive the deploy.
  //
  // Generate a value with:  openssl rand -base64 32
  // ──────────────────────────────────────────────────────────────────
}

module.exports = nextConfig