import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import type { IOrderModuleService } from "@medusajs/framework/types"
import { Modules } from "@medusajs/framework/utils"
import { z } from "zod"
import { ulid } from "ulid"

const uploadSchema = z.object({
  line_item_id: z.string().min(1),
  side: z.string().min(1),
  // File upload path
  filename: z.string().min(1).max(200).optional(),
  mime_type: z.string().min(1).max(80).optional(),
  data_base64: z.string().optional(),
  // URL-only path (proof generated by the admin customiser iframe)
  mockup_url: z.string().url().max(2048).optional(),
  artwork_url: z.string().url().max(2048).optional(),
  note: z.string().max(500).optional(),
}).refine(
  (d) => !!d.data_base64 || !!d.mockup_url,
  { message: "Either data_base64 (file upload) or mockup_url (URL-only) is required" }
)

const MAX_BYTES = 8 * 1024 * 1024 // 8 MB

export type RevisedProof = {
  id: string
  line_item_id: string
  side: string
  url: string
  filename: string
  mime_type: string
  /** Raw artwork URL — set when the proof was generated via the admin customiser
   *  iframe so staff can re-open it for further repositioning.
   *  Null for proofs uploaded as a flat image (the upload IS the proof). */
  artwork_url?: string | null
  note?: string | null
  uploaded_at: string
  uploaded_by?: string | null
}

/**
 * POST /admin/orders/:id/revised-proof
 *   Accepts two modes:
 *   1. File upload: { line_item_id, side, filename, mime_type, data_base64, note? }
 *      → uploads to MinIO, stores URL as `proof.url` (and `proof.artwork_url`)
 *   2. URL-only:   { line_item_id, side, mockup_url, artwork_url?, note? }
 *      → no upload, stores provided URLs directly
 *   Both return → { proof: RevisedProof, proofs: RevisedProof[] }
 *
 * GET  → { proofs: RevisedProof[] }
 * DELETE ?id=<proofId> → { proofs: RevisedProof[] }
 */
export async function POST(req: MedusaRequest, res: MedusaResponse) {
  const orderId = req.params.id
  if (!orderId) return res.status(400).json({ error: "id required" })

  let parsed: z.infer<typeof uploadSchema>
  try {
    parsed = uploadSchema.parse(req.body ?? {})
  } catch (err: any) {
    return res.status(400).json({ error: err?.message ?? "Invalid request" })
  }

  const orderModuleService: IOrderModuleService = req.scope.resolve(Modules.ORDER)
  let order: any
  try {
    order = await orderModuleService.retrieveOrder(orderId)
  } catch {
    return res.status(404).json({ error: "Order not found" })
  }

  const meta = (order.metadata ?? {}) as Record<string, unknown>
  const existing: RevisedProof[] = Array.isArray(meta.revised_proofs)
    ? (meta.revised_proofs as RevisedProof[])
    : []

  let proof: RevisedProof

  if (parsed.mockup_url) {
    // URL-only path — customiser iframe already rendered the mockup
    proof = {
      id: ulid(),
      line_item_id: parsed.line_item_id,
      side: parsed.side,
      url: parsed.mockup_url,
      filename: parsed.mockup_url.split("/").pop()?.split("?")[0] ?? "proof.jpg",
      mime_type: "image/jpeg",
      artwork_url: parsed.artwork_url ?? null,
      note: parsed.note ?? null,
      uploaded_at: new Date().toISOString(),
      uploaded_by: (req as any).auth_context?.actor_id ?? null,
    }
  } else {
    // File upload path
    const base64 = (parsed.data_base64 ?? "").replace(/^data:[^;]+;base64,/, "")
    let buffer: Buffer
    try {
      buffer = Buffer.from(base64, "base64")
    } catch {
      return res.status(400).json({ error: "data_base64 is not valid base64" })
    }
    if (buffer.byteLength === 0) {
      return res.status(400).json({ error: "Empty payload" })
    }
    if (buffer.byteLength > MAX_BYTES) {
      return res.status(413).json({ error: "File exceeds 8 MB limit" })
    }
    const mimeType = parsed.mime_type ?? "image/jpeg"
    if (!mimeType.startsWith("image/")) {
      return res.status(400).json({ error: "Only image uploads are accepted" })
    }

    let fileModuleService: { createFiles: (data: { filename: string; mimeType: string; content: string }[]) => Promise<Array<{ id: string; url: string }>> }
    try {
      fileModuleService = req.scope.resolve(Modules.FILE) as typeof fileModuleService
    } catch (err: any) {
      return res.status(500).json({ error: "File module not available", detail: String(err?.message ?? err) })
    }

    const filename = parsed.filename ?? "proof.jpg"
    const safeName = `revised-proofs/${orderId}/${parsed.side}/${Date.now()}-${filename.replace(/[^a-zA-Z0-9._-]/g, "_")}`
    let uploaded: Array<{ id: string; url: string }>
    try {
      uploaded = await fileModuleService.createFiles([
        { filename: safeName, mimeType, content: base64 },
      ])
    } catch (err: any) {
      return res.status(500).json({ error: "Upload failed", detail: String(err?.message ?? err) })
    }
    if (!uploaded?.[0]?.url) {
      return res.status(500).json({ error: "Upload returned no URL" })
    }

    proof = {
      id: ulid(),
      line_item_id: parsed.line_item_id,
      side: parsed.side,
      url: uploaded[0].url,
      filename,
      mime_type: mimeType,
      artwork_url: uploaded[0].url, // uploaded file is itself the artwork for re-editing
      note: parsed.note ?? null,
      uploaded_at: new Date().toISOString(),
      uploaded_by: (req as any).auth_context?.actor_id ?? null,
    }
  }

  const proofs = [...existing, proof]
  try {
    await orderModuleService.updateOrders(orderId, {
      metadata: { ...meta, revised_proofs: proofs },
    })
  } catch (err: any) {
    return res.status(500).json({ error: "Failed to save proof", detail: String(err?.message ?? err) })
  }

  res.status(201).json({ proof, proofs })
}

export async function GET(req: MedusaRequest, res: MedusaResponse) {
  const orderId = req.params.id
  const orderModuleService: IOrderModuleService = req.scope.resolve(Modules.ORDER)
  let order: any
  try {
    order = await orderModuleService.retrieveOrder(orderId)
  } catch {
    return res.status(404).json({ error: "Order not found" })
  }
  const meta = (order.metadata ?? {}) as Record<string, unknown>
  const proofs: RevisedProof[] = Array.isArray(meta.revised_proofs)
    ? (meta.revised_proofs as RevisedProof[])
    : []
  res.json({ proofs })
}

export async function DELETE(req: MedusaRequest, res: MedusaResponse) {
  const orderId = req.params.id
  const proofId = String((req.query?.id as string) ?? "")
  if (!proofId) return res.status(400).json({ error: "id query param required" })

  const orderModuleService: IOrderModuleService = req.scope.resolve(Modules.ORDER)
  let order: any
  try {
    order = await orderModuleService.retrieveOrder(orderId)
  } catch {
    return res.status(404).json({ error: "Order not found" })
  }
  const meta = (order.metadata ?? {}) as Record<string, unknown>
  const proofs: RevisedProof[] = Array.isArray(meta.revised_proofs)
    ? (meta.revised_proofs as RevisedProof[])
    : []
  const next = proofs.filter((p) => p?.id !== proofId)
  await orderModuleService.updateOrders(orderId, {
    metadata: { ...meta, revised_proofs: next },
  })
  res.json({ proofs: next })
}
